### PR TITLE
Fix deprecation warnings until the plugin uses the new W3C endpoint

### LINKED ISSUE #22: HTML5 checking deprecated
I'm receiving a new error saying that the HTML5 checking is deprecated now.

### PR DESCRIPTION
**Pull request by raphinesse**
Gives us some more time to fix #22

### CODE REVIEW

**Comment by nikestep** [comment]
I'm going to close this as I was able to upgrade and fix the issue, so this isn't necessary anymore. Thank you for the help, though!

**Comment by raphinesse** [comment]
I think this is still necessary. Right now there's the 0.5.0 release with breaking changes (old `relaxerrors` don't work anymore, because of the changed wording) and the 0.4.1 release that shows the deprecation warnings all over the place, failing builds too.

If you would release this fixed version as 0.4.2, maybe giving *one* deprecation warning from the plugin itself, without failing the build, this would give *users* of the plugin more time to fix their builds.

**Comment by nikestep** [comment]
This is a good point; I had not considered it this way. I have created and published a v0.4.2 using your change. I'm not a git master, so I did it without committing the change, but it's in npm for use. The latest version of the plugin remains 0.5.0.

**Comment by chriskuehl** [comment]
this is awesome, thanks both of you for your work!

**Pull request closed without merging**
